export type DetailTableName = "companies" | "contacts" | "opportunities";

export type DetailField = { key: string; label: string };

export const DETAIL_FIELD_CATALOG: Record<DetailTableName, DetailField[]> = {
  companies: [
    { key: "nombre_dominio_empresa", label: "Nombre de dominio de la empresa" },
    { key: "industry", label: "Industria" },
    { key: "numero_telefono", label: "Número de teléfono" },
    { key: "etapa_ciclo_vida", label: "Etapa del ciclo de vida" },
    { key: "ultimo_contacto", label: "Último contacto" },
    { key: "tax_id", label: "NIF / CIF" },
    { key: "fiscal_address", label: "Dirección fiscal" },
    { key: "fecha_creacion", label: "Fecha de creación" },
    { key: "fecha_ultima_modificacion", label: "Fecha de última modificación" },
    { key: "direccion", label: "Dirección" },
    { key: "direccion_2", label: "Dirección 2" },
    { key: "ciudad", label: "Ciudad" },
    { key: "estado_region", label: "Estado/Región" },
    { key: "codigo_postal", label: "Código postal" },
    { key: "pais_region", label: "País/Región" },
    { key: "descripcion", label: "Descripción" },
    { key: "industria", label: "Industria (CNAE/texto libre)" },
    { key: "ingresos_anuales", label: "Ingresos anuales" },
    { key: "numero_empleados", label: "Número de empleados" },
    { key: "pagina_empresa_linkedin", label: "Página de la empresa en LinkedIn" },
    { key: "tipo", label: "Tipo" },
    { key: "fuente_registro", label: "Fuente del registro" },
    { key: "estado_oportunidad_venta", label: "Estado de la oportunidad de venta" },
    { key: "fecha_cierre_se_hizo_cliente", label: "Fecha de cierre (se hizo cliente)" },
    { key: "fuente_trafico_original", label: "Fuente de tráfico original" },
    { key: "ultima_fuente_trafico", label: "Última fuente de tráfico" },
    { key: "desglose_fuente_original_1", label: "Desglose de la fuente original 1" },
    { key: "desglose_fuente_original_2", label: "Desglose de la fuente original 2" },
    { key: "datos_ultima_fuente_1", label: "Datos de la última fuente 1" },
    { key: "datos_ultima_fuente_2", label: "Datos de la última fuente 2" },
    { key: "fecha_ultima_fuente_trafico", label: "Fecha de la última fuente de tráfico" },
    { key: "primera_conversion", label: "Primera conversión" },
    { key: "fecha_primera_conversion", label: "Fecha de primera conversión" },
    { key: "conversion_reciente", label: "Conversión reciente" },
    { key: "fecha_conversion_reciente", label: "Fecha de conversión reciente" },
  ],
  contacts: [
    { key: "correo_electronico", label: "Correo electrónico" },
    { key: "numero_telefono", label: "Número de teléfono" },
    { key: "numero_telefono_movil", label: "Número de teléfono móvil" },
    { key: "phone_country", label: "País (teléfono)" },
    { key: "company", label: "Empresa" },
    { key: "nombre_empresa", label: "Nombre de la empresa (texto libre)" },
    { key: "fuente_trafico_original", label: "Fuente de tráfico original" },
    { key: "ultima_fuente_trafico", label: "Última fuente de tráfico" },
    { key: "desglose_fuente_original_1", label: "Desglose de la fuente original 1" },
    { key: "desglose_fuente_original_2", label: "Desglose de la fuente original 2" },
    { key: "source_url", label: "URL de origen" },
    { key: "id_clic_google_ads_gclid", label: "ID de clic de Google Ads (GCLID)" },
    { key: "id_clic_facebook_fbclid", label: "ID de clic de Facebook (FBCLID)" },
    { key: "etapa_ciclo_vida", label: "Etapa del ciclo de vida" },
    { key: "estado_lead", label: "Estado del lead" },
    { key: "cancelacion_suscripcion_todos_correos", label: "Cancelación de suscripción a todos los correos" },
    { key: "tax_id", label: "NIF" },
    { key: "fiscal_address", label: "Dirección fiscal" },
    { key: "ultimo_contacto", label: "Último contacto" },
    { key: "fecha_ultima_modificacion", label: "Fecha de última modificación" },
    { key: "ciudad", label: "Ciudad" },
    { key: "estado_region", label: "Estado/Región" },
    { key: "codigo_postal", label: "Código postal" },
    { key: "pais_region", label: "País/Región" },
    { key: "direccion", label: "Dirección" },
    { key: "cargo", label: "Cargo" },
    { key: "industria", label: "Industria" },
    { key: "url_sitio_web", label: "URL del sitio web" },
    { key: "url_linkedin", label: "URL de LinkedIn" },
    { key: "mensaje", label: "Mensaje" },
    { key: "correos_electronicos_adicionales", label: "Correos electrónicos adicionales" },
    { key: "contacto_sin_gestionar", label: "¿Contacto sin gestionar?" },
    { key: "fuente_registro", label: "Fuente del registro" },
    { key: "base_juridica_tratamiento_datos", label: "Base jurídica para el tratamiento de datos" },
    { key: "desglose_ultima_fuente_1", label: "Desglose de la última fuente 1" },
    { key: "desglose_ultima_fuente_2", label: "Desglose de la última fuente 2" },
    { key: "fecha_ultima_fuente_trafico", label: "Fecha de la última fuente de tráfico" },
    { key: "primera_conversion", label: "Primera conversión" },
    { key: "fecha_primera_conversion", label: "Fecha de primera conversión" },
    { key: "conversion_reciente", label: "Conversión reciente" },
    { key: "fecha_conversion_reciente", label: "Fecha de conversión reciente" },
    { key: "fecha_siguiente_actividad", label: "Fecha de la siguiente actividad" },
    { key: "direccion_correo_no_valida", label: "Dirección de correo no válida" },
    { key: "fecha_cierre_se_hizo_cliente", label: "Fecha de cierre (se hizo cliente)" },
  ],
  opportunities: [
    { key: "company", label: "Empresa" },
    { key: "contact", label: "Contacto" },
    { key: "amount", label: "Importe" },
    { key: "notes", label: "Notas" },
    { key: "created_at", label: "Creada" },
    { key: "fecha_cierre", label: "Fecha de cierre" },
    { key: "ultimo_contacto", label: "Último contacto" },
    { key: "fuente_trafico_original", label: "Fuente de tráfico original" },
    { key: "desglose_fuente_original_1", label: "Desglose de la fuente original 1" },
    { key: "desglose_fuente_original_2", label: "Desglose de la fuente original 2" },
    { key: "esta_cerrado_ganado", label: "Está cerrado ganado" },
    { key: "esta_cerrado_perdido", label: "Está cerrado perdido" },
    { key: "fecha_ultima_modificacion", label: "Fecha de última modificación" },
    { key: "tipo_negocio", label: "Tipo de negocio" },
    { key: "siguiente_paso", label: "Siguiente paso" },
    { key: "fuente_registro", label: "Fuente del registro" },
    { key: "probabilidad_negocio", label: "Probabilidad de negocio" },
    { key: "valor_ponderado", label: "Valor ponderado" },
    { key: "motivo_cierre_ganado", label: "Motivo del cierre ganado" },
    { key: "motivo_cierre_perdido", label: "Motivo del cierre perdido" },
    { key: "ultima_fuente_trafico", label: "Última fuente de tráfico" },
    { key: "desglose_ultima_fuente_1", label: "Desglose de la última fuente 1" },
    { key: "desglose_ultima_fuente_2", label: "Desglose de la última fuente 2" },
    { key: "descripcion_negocio", label: "Descripción del negocio" },
    { key: "prioridad", label: "Prioridad" },
    { key: "categoria_prevision", label: "Categoría de previsión" },
    { key: "ingresos_recurrentes_mensuales_mrr", label: "Ingresos recurrentes mensuales (MRR)" },
  ],
};

export const DEFAULT_DETAIL_FIELDS: Record<DetailTableName, string[]> = {
  companies: ["nombre_dominio_empresa", "industry", "tax_id", "fiscal_address"],
  contacts: ["correo_electronico", "numero_telefono", "company", "fuente_trafico_original"],
  opportunities: ["company", "amount", "notes"],
};

export function resolveDetailFields(tableName: DetailTableName, saved: string[] | null | undefined): DetailField[] {
  const catalog = DETAIL_FIELD_CATALOG[tableName];
  const keys = saved && saved.length > 0 ? saved : DEFAULT_DETAIL_FIELDS[tableName];
  return keys.map((key) => catalog.find((f) => f.key === key)).filter((f): f is DetailField => Boolean(f));
}
